Traceback (most recent call last):
  File "/Users/shofmann/micromamba/envs/miraca-book/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/shofmann/micromamba/envs/miraca-book/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/shofmann/micromamba/envs/miraca-book/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/shofmann/micromamba/envs/miraca-book/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/shofmann/micromamba/envs/miraca-book/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/shofmann/micromamba/envs/miraca-book/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/shofmann/micromamba/envs/miraca-book/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Importing packages

import geopandas as gpd
import pandas as pd
import os
import rioxarray as rio
import matplotlib.pyplot as plt
import numpy as np
from rasterstats import zonal_stats
from scipy.interpolate import interp1d
from table import sut_basic
from mria_new_SUT import MRIA_SUT as MRIAnew
from pyomo.environ import value
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 3[0m
[1;32m      1[0m [38;5;66;03m# Importing packages[39;00m
[0;32m----> 3[0m [38;5;28;01mimport[39;00m [38;5;21;01mgeopandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mgpd[39;00m
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[1;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mos[39;00m

[0;31mModuleNotFoundError[0m: No module named 'geopandas'

